#############################################################################
# Makefile for building: Gomoku
# Generated by qmake (2.01a) (Qt 4.8.5) on: Mon Nov 11 22:15:23 2013
# Project:  Gomoku.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile Gomoku.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.moc
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		frame.cpp \
		player.cpp \
		arbiter.cpp \
		changecolor.cpp \
		menu.cpp \
		game.cpp \
		settings.cpp .moc/moc_mainwindow.cpp \
		.moc/moc_frame.cpp \
		.moc/moc_menu.cpp \
		.moc/moc_game.cpp \
		.moc/moc_settings.cpp
OBJECTS       = .obj/main.o \
		.obj/mainwindow.o \
		.obj/frame.o \
		.obj/player.o \
		.obj/arbiter.o \
		.obj/changecolor.o \
		.obj/menu.o \
		.obj/game.o \
		.obj/settings.o \
		.obj/moc_mainwindow.o \
		.obj/moc_frame.o \
		.obj/moc_menu.o \
		.obj/moc_game.o \
		.obj/moc_settings.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		Gomoku.pro
QMAKE_TARGET  = Gomoku
DESTDIR       = 
TARGET        = Gomoku

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gomoku.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile Gomoku.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/modules/qt_webkit.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile Gomoku.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/Gomoku1.0.0 || $(MKDIR) .obj/Gomoku1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/Gomoku1.0.0/ && $(COPY_FILE) --parents mainwindow.h frame.h player.h arbiter.h changecolor.h menu.h game.h settings.h .obj/Gomoku1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp frame.cpp player.cpp arbiter.cpp changecolor.cpp menu.cpp game.cpp settings.cpp .obj/Gomoku1.0.0/ && (cd `dirname .obj/Gomoku1.0.0` && $(TAR) Gomoku1.0.0.tar Gomoku1.0.0 && $(COMPRESS) Gomoku1.0.0.tar) && $(MOVE) `dirname .obj/Gomoku1.0.0`/Gomoku1.0.0.tar.gz . && $(DEL_FILE) -r .obj/Gomoku1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_mainwindow.cpp .moc/moc_frame.cpp .moc/moc_menu.cpp .moc/moc_game.cpp .moc/moc_settings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_mainwindow.cpp .moc/moc_frame.cpp .moc/moc_menu.cpp .moc/moc_game.cpp .moc/moc_settings.cpp
.moc/moc_mainwindow.cpp: menu.h \
		game.h \
		arbiter.h \
		frame.h \
		player.h \
		settings.h \
		changecolor.h \
		mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o .moc/moc_mainwindow.cpp

.moc/moc_frame.cpp: frame.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) frame.h -o .moc/moc_frame.cpp

.moc/moc_menu.cpp: menu.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) menu.h -o .moc/moc_menu.cpp

.moc/moc_game.cpp: arbiter.h \
		frame.h \
		player.h \
		settings.h \
		changecolor.h \
		game.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) game.h -o .moc/moc_game.cpp

.moc/moc_settings.cpp: settings.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) settings.h -o .moc/moc_settings.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: .ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.obj/main.o: main.cpp mainwindow.h \
		menu.h \
		game.h \
		arbiter.h \
		frame.h \
		player.h \
		settings.h \
		changecolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		menu.h \
		game.h \
		arbiter.h \
		frame.h \
		player.h \
		settings.h \
		changecolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mainwindow.o mainwindow.cpp

.obj/frame.o: frame.cpp frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frame.o frame.cpp

.obj/player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/player.o player.cpp

.obj/arbiter.o: arbiter.cpp arbiter.h \
		frame.h \
		player.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/arbiter.o arbiter.cpp

.obj/changecolor.o: changecolor.cpp changecolor.h \
		player.h \
		frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/changecolor.o changecolor.cpp

.obj/menu.o: menu.cpp menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/menu.o menu.cpp

.obj/game.o: game.cpp game.h \
		arbiter.h \
		frame.h \
		player.h \
		settings.h \
		changecolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/game.o game.cpp

.obj/settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/settings.o settings.cpp

.obj/moc_mainwindow.o: .moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mainwindow.o .moc/moc_mainwindow.cpp

.obj/moc_frame.o: .moc/moc_frame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_frame.o .moc/moc_frame.cpp

.obj/moc_menu.o: .moc/moc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_menu.o .moc/moc_menu.cpp

.obj/moc_game.o: .moc/moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_game.o .moc/moc_game.cpp

.obj/moc_settings.o: .moc/moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_settings.o .moc/moc_settings.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

